### ISSUE TITLE
How to do style reference.

### ISSUE THREAD

**Issue by Adenialzz** [DarkMnDragon/rf-inversion-diffuser#2]
Hi, thanks for sharing your reimplementation. I wonder how can I do style reference using rf-inversion (like fig. 1 in paper).

**Comment by CyberDragon93** [comment]
Hi, Thanks for your question. In my experiments and subsequent work, **I personally believe that RF-inversion-like editing methods cannot effectively support style reference**. 

First, You can try subject substitutions / stylization with my notebook using an inversion-free approach (i.e., set `use_inversed_latents=False`) to get a feeling of how the editing process works. With careful tuning of the $\eta$ values, you can achieve comparable or even better results with original RF-inversion.

Essentially, this type of control works by interpolating between two velocities (as I’ve annotated in the code), where the control term represents the analytic form of the rectified flow velocity when there is only a single data point. It’s akin to performing guidance using a real image. Through this approach, subject substitution or stylization can certainly be achieved because, during the early stage of the flow, the guidance primarily contains low-frequency information (e.g., contours and shapes). That’s why high $\eta$ values should be injected at the initial phase. 

The stylization you mentioned happens because the injection of color information in the early stages realizes this style—or more specifically, just the color. However, achieving abstract styles, such as Van Gogh’s *Starry Night*, is not feasible with this approach, as it essentially direct image guidance doesn't have this abstract style information.

**Comment by CyberDragon93** [comment]
![QQ_1731913584368](https://github.com/user-attachments/assets/16ded14f-4c91-4c16-ada9-302d7a4ef9f4)

Time increases in row order
